Joel/page-index
Joel-leal/voting-system pull request #21
Opened 2022-06-21 00:42 UTC by Joel-leal

### **Description**
  
 Criar página de home onde o cliente poderá escolher qual eleiçvão participar.

### **changes**

 * Criado um titulo 
 * Criado um select para a primeira eleição
 
 Close
 
 #4

2022-06-21 13:13 UTC, frattezi requested changes
Acho que o select ainda está meio estranho. Talvez, adicionando o botão ao seu lado, evitando que ele ocupe a box toda e fique muito largo evite maiores distorções. 🚀

2022-06-21 13:13 UTC, frattezi commented on pages/index.tsx
> +        <main>
Não gostei da parte visual, vi vários probleminhas na página que não deveriam ocorrer:
- A seta do select está deslocada para cima.
- Poderia haver uma maior separação entre h1 e select
- Paddings laterais parecem diferentes.

O menu do select estar descolado, como haviámos conversado anteriormente, não ocorre no linux. 
![image](https://user-images.githubusercontent.com/14007745/174805509-fc502b0a-c86c-4690-8f0c-e8045adf56ef.png)

2022-06-21 13:13 UTC, frattezi commented on pages/index.tsx
> +              </Select>
Não foi adicionado um botão de confirmação para o select, o botão de inciar a eleição

2022-06-21 14:28 UTC, marco-souza commented on pages/index.tsx
> +        <main>
Talvez precisemos de uma lib para fazer o select melhor. Aqui usamos `react-select`.

2022-06-21 17:17 UTC, Joel-leal commented on pages/index.tsx
> +        <main>
Mas vamos add essa biblioteca?

2022-06-21 19:55 UTC, frattezi commented on pages/index.tsx
> +        <main>
Se conseguir resolver sem, não. Se não, siga o padrão do webapp e vamos dar prosseguimento

2022-06-22 13:06 UTC, frattezi commented
page-index para o nome?
Aqui você quer geralmente escrever uma frase mesmo, descrevendo a ação que você está fazendo, logo conterá um verbo, como

"Add new first page to project"
"Crate index page for the app"

Algo assim, você quer descrever para o revisor oque você fez em uma frase simples.

2022-06-22 22:28 UTC, frattezi commented
@Joel-leal mergeei o pr com o endpoint utilizado por este carinha, já pode consumir ele, pode separar em 2 pr's também

2022-06-28 13:30 UTC, frattezi commented on pages/index.tsx
> +              <option value="sexto-ano">Sexto-ano</option>
Meu comment sobre a geração de lista ainda vale, apesar de outdated

2022-06-29 17:13 UTC, frattezi submitted a review, later dismissed
Só mais um pequeno detalhe e pode mergear

2022-06-29 17:13 UTC, frattezi commented on pages/index.tsx
> +              Buscar
A frase para este botão deveria ser algo como: "Iniciar eleição"

2022-06-29 17:17 UTC, Joel-leal commented on pages/index.tsx
> +              Buscar
Iniciar eleição ou iniciar votação?

2022-06-29 18:20 UTC, frattezi commented
Poderia também mudar o nome deste PR de page-index para algo mais descritivo como
feat: add election select for index page

2022-06-29 20:06 UTC, merged